steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--tag', 'gcr.io/sfdc24/expert_image:latest', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/expert-deployment', 'expert-container=gcr.io/sfdc24/expert_image:latest']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sfdc24'

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'pool1'
