name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build site
      run: bundle exec jekyll build --baseurl ""

    - name: Deploy to GitHub Pages
      uses: actions/configure-pages@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
